import { logo } from "../types";

export const switchesData: logo[] = [
  { name: "lightbulb" },
  { name: "lightbulb-outline" },
  { name: "lightbulb-fluorescent-tube" },
  { name: "lightbulb-fluorescent-tube-outline" },
  { name: "lightbulb-on" },
  { name: "lightbulb-on-outline" },
  { name: "home-lightbulb" },
  { name: "home-lightbulb-outline" },
  { name: "fan" },
  { name: "fan-speed-1" },
  { name: "fan-speed-2" },
  { name: "fan-speed-3" },
  { name: "ceiling-fan" },
  { name: "ceiling-fan-light" },
  { name: "air-conditioner" },
  { name: "air-filter" },
  { name: "air-humidifier" },
  { name: "air-purifier" },
  { name: "television" },
  { name: "television-classic" },
  { name: "fridge" },
  { name: "fridge-outline" },
  { name: "fridge-industrial" },
  { name: "fridge-industrial-outline" },
  { name: "fridge-top" },
  { name: "fridge-variant" },
  { name: "fridge-variant-outline" },
  { name: "water-boiler" },
  { name: "radiator" },
  { name: "patio-heater" },
];

export const devicesData: logo[] = [
  {name:"home"},
  {name:"hoop-house"},
  {name:"home-modern"},
  {name:"greenhouse"},
  {name:"bed"},
  {name:"bed-outline"},
  {name:"sofa"},
  {name:"sofa-outline"},
  {name:"bed-queen"},
  {name:"shower"},
  {name:"toilet"},
  {name:"countertop"},
  {name:"countertop-outline"},
  {name:"table-chair"},
  {name:"food-turkey"},
]